### ISSUE TITLE
Conflict with "Re-Chiseled" and "Gauges and Switches" mods

### ISSUE THREAD

**Issue by SvyatoSvin** [TheOriginalGolem/Hbm-s-Nuclear-Tech-GIT#19]
I use TLauncher and when I try to run these three mods I get errors, tell me, these mods can't work together, or is it a Launcher problem?

**Comment by NoMoreUsernames999** [comment]
Considering the fact that 90% of players that use Tlauncher do so because it allows playing with a cracked client, it is more likely the fact that cracked clients are buggy as hell. Did you buy the game or are you using a pirated copy? You should be using ATlauncher, Curse launcher, or multimc if you have a legit copy of the game. if not, then there is nothing you can do.

**Comment by TheOriginalGolem** [comment]
Closed due to the high possibility of being a cracked user.
